# Generated by Django 4.1.3 on 2022-11-23 18:29

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_location_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.us.models.USStateField(default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
    ]
