# Generated by Django 4.1.3 on 2022-11-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_listing_engine_alter_listing_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to='Asupercharge/main/pics'),
        ),
    ]
