# Generated by Django 4.1.3 on 2022-11-27 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='seller',
        ),
    ]
