# Generated by Django 4.1.3 on 2022-11-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_owner_listing_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='owner',
        ),
    ]
